### PR TITLE
#4 Vaccine sdtm data

### PR DESCRIPTION
**Pull request by arjoon-r**
Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiraldev/main/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [x] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [ ] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [ ] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://pharmaverse.github.io/admiraldev/main/articles/unit_test_guidance.html#writing-unit-tests-in-admiral)
- [ ] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiraldev/main/articles/programming_strategy.html#deprecation)?
- [ ] Update to all relevant roxygen headers and examples.
- [ ] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [ ] Address any updates needed for vignettes and/or templates
- [ ] Update `NEWS.md` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [ ] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page.
- [ ] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [ ] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [ ] Link the issue so that it closes after successful merging.
- [ ] Address all merge conflicts and resolve appropriately.
- [ ] Pat yourself on the back for a job well done! Much love to your accomplishment!

### CODE REVIEW

**Comment by bms63** [comment]
We need to create a script in the R folder called `data.R` that has documenation on these datasets 
image

Check out https://github.com/pharmaverse/admiral.test/blob/main/R/data.R to see how it is set up.  Be sure to run `devtools::document()` to get updated `man` files.

**Comment by yangc71** [comment]
As a general comment for creating pull requests, please link the relevant issue to the pull reques, and create the pull request with format "Close #issue_number: short description of pull request". Please reference the "Pull Request" section of the [admiraldev git usage guide](https://pharmaverse.github.io/admiraldev/main/articles/git_usage.html#pull-request) for more information.

**Comment by bms63** [comment]
@arjoon-r  I think the object has to be called `admiralvaccine_ex` as well as being saved as `admiralvaccine_ex` to work.  If you just rename the `rda` file with admiralvaccine_ex, then the package still sees it as the original ex dataset.

**Comment by bms63** [comment]
@arjoon-r We will need to work on naming convention for this data and process for updating/maintaining it.  Going to merge into `devel/main`

**Pull request merged**
